---
abstract: 'Expand any URL shortener link'
author:
  - 'Konrad Borowski <glitchmr@myopera.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Expand
requires:
  Carp: 0
  Exporter: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  strictures: 1
resources:
  bugtracker: https://github.com/GlitchMr/WWW-Expand/issues
  repository: git://github.com/GlitchMr/WWW-Expand.git
version: 0.1.0
